### ISSUE TITLE
how to pair airsonic with nextcloud shared music folder ??

### ISSUE THREAD

**Issue by gilluc** [YunoHost-Apps/airsonic_ynh#16]
it seems to be obvious that airsonic should be able to play files from nextcloud multimedia/music and shared/music, isnt it?
gilles
how to "connect" nextcloud folders to airsonic folders ???
ln -s what where ??

**Comment by gilluc** [comment]
just found it in airsonic setting ... sorry

**Comment by kay0u** [comment]
Hi, it should be done during the install:

https://github.com/YunoHost-Apps/airsonic_ynh/pull/12

**Comment by gilluc** [comment]
problem already fixed....
thanks kayOu
