### ISSUE TITLE
Unable to login with user after initial install

### ISSUE THREAD

**Issue by GiantZOC** [YunoHost-Apps/airsonic_ynh#17]
Hello,
I just did a fresh install of Airsonic and am unable to login.  I tried logging in through SSO and through the site directly with my user.  I get the message Incorrect username or password.  I got a more detailed error message through SSO which I have attached. 

![Screenshot from 2020-01-03 16-28-27](https://user-images.githubusercontent.com/5790244/71754287-2536e180-2e4b-11ea-9ccb-1e22d6cb2c60.png)

I found some related errors on the Airsonic page but they are unresolved.  It might just be an issue with the docker image.  https://github.com/airsonic/airsonic/issues/893
https://github.com/airsonic/airsonic/issues/1047

**Comment by kay0u** [comment]
Hi,
Which Yunohost version you use?

**Comment by GiantZOC** [comment]
Hello,
It was on a fresh install of yunohost version 3.6.5.3.

**Comment by GiantZOC** [comment]
I did some further digging into the issue.  It looks like the SSO is not working for me.  I tested SSO with another application and it was working fine.  I see that the script is setting the admin password to some random value.  I also tried a password reset but the SMTP settings are not configured.

**Comment by GiantZOC** [comment]
I was able to login by providing my username instead of my email.  I also got the SMTP working by altering the airsonic.properties file manually.

**Comment by kay0u** [comment]
Thank you for your feedback!

Ha yes indeed, you have to use your username. If you want to patch this, PR are welcome :-)
