### ISSUE TITLE
[feature] add action script to reset admin password

### ISSUE THREAD

**Issue by Gofannon** [YunoHost-Apps/airsonic_ynh#18]
Following https://github.com/YunoHost-Apps/airsonic_ynh/issues/17#issuecomment-571237511, it should be useful to be able to reset the admin password from the admin panel

TODO
- [ ] create PR to trace work in progress
- [ ] create action script
- [ ] create action panel

TO IMPLEMENT
- [ ] reset airsonic password
- [ ]  change password in app setiing
- [ ] Ability to send mail ?

**Comment by kay0u** [comment]
It's not needed (IMO) because we grant admin role to the user gave at installation:

https://github.com/YunoHost-Apps/airsonic_ynh/blob/ae8e4634be06f5e210371a828c488d1728977507/scripts/install#L248

**Comment by Gofannon** [comment]
You're right. No need for this!
