### ISSUE TITLE
Unable to connect from DSub

### ISSUE THREAD

**Issue by Aeris1One** [YunoHost-Apps/airsonic_ynh#23]
Hi,
I've some issues with airsonic.
I installed airsonic and put some MP3 files into /home/yunohost.multimedia/share/Music and then refreshed list from admin settings. There's "23 artists, 28 albums,..." on the footer but I can't see any music, the home page seems empty.
And I'm not able to connect with DSub (or any subsonic client for Android) : "incorrect username or password" even if there're corrects.
As I'm a newbie with airsonic, is there anything I've to do ?

**Comment by Aeris1One** [comment]
Solved, I've to go in Admin settings, then user, select my user, disable LDAP Authentication, set a custom password and autorize access to Yunohost folder.

**Comment by kay0u** [comment]
Hi,

Weird, it works well for me with ldap (app Substreamer)
