### ISSUE TITLE
[Buster] Stuck to level 2 because can't install old commit to test upgrade

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/airsonic_ynh#24]
2a0dd05780f58cb2590c05eabab3669381ac65ce still has the old dependency requirement ... so upgrade from that commit can't be tested and thereforce the buster CI reports are stuck at level 2 though this app is probably level 7 in practice...

Dunno what do about this, but at least I report it here so the "regression" is understood.

**Comment by Gofannon** [comment]
I'm not sure I understand correctly the problem

Does it mean that this file needs to be changed? https://github.com/YunoHost-Apps/airsonic_ynh/blob/master/check_process Specificaly the commit referred?
I never really understood which "commit id" to put here ...

**Comment by alexAubin** [comment]
I'm not sure either

The idea is to test the upgrade from some old commit, and I'd say you want to do this when you want to make sure a complex migration was added and want to keep checking that this migration runs well from that old commit.

With that said, after 1-2 year it's probably fine to remove that test (idk from when that commit dates back in our case)

Anyway, if we want to be super careful, I guess we can indeed try to add some sort of pseudo-branch with a commit that fixes the buster install way back then ... (though then we may run in other issues)

Or we can just forget about it for now and focus on apps with bigger issues :P

**Comment by Gofannon** [comment]
Fixed by https://github.com/YunoHost-Apps/airsonic_ynh/pull/26

See buster ci: https://ci-buster.nohost.me/ci/job/453



> Or we can just forget about it for now and focus on apps with bigger issues :P

Agree with this :)

**Comment by alexAubin** [comment]
Thanks ! :heart:
