### ISSUE TITLE
Airsonic unable to read /home/yunohost.multimedia/share/Music

### ISSUE THREAD

**Issue by JOduMonT** [YunoHost-Apps/airsonic_ynh#3]
Hi;

It might be a big presomption but I tought airsonic will be able to read the music in the shared folder : `/home/yunohost.multimedia/share/Music`

**Comment by Gofannon** [comment]
Hello,

At the moment, Airsonic cannot install the "multimedia package" but it can use if it is installed (by an other app)

In "media folders", have you tried to add a share "multimedia_ynh" aiming to "/home/yunohost.multimedia" ?
On my server, I have access to music downloaded by Transmission this way

**Comment by kay0u** [comment]
Hi, this should be closed by #12. Can you confirm that?

**Comment by kay0u** [comment]
I'm closing this issue, feel free to reopen it if needed
