### ISSUE TITLE
Airsonic unreachable if url was changed

### ISSUE THREAD

**Issue by Globlonux01** [YunoHost-Apps/airsonic_ynh#31]
Hi, when you choose to change the URL of airsonic, It can't be reacheable.
In this case, you will see a 502 bad gateway error or you will be redirected to the SSO App interface

need to unistall all airsonic app, and reinstall if you want change the url

**Comment by Flatrongraad** [comment]
Hi there, bit late for a reply on something from april :sweat_smile: , trick is I had the same issue when simply restarting the server at home and looking at the install script, I saw that the last item is a reload of nginx service. 
So workaround is to go to the admin page Services > nginx and hit the restart button. You'll have to log back in and airsonic should be working.
There's something not going right when either changing the URL or restarting :thinking: 

Hope that helps!

**Comment by stevenmache** [comment]
+1
I had the sake issue when changing to my own domain. Orignal post [here](https://forum.yunohost.org/t/various-errors-on-domain-change/15163/11)

**Comment by yalh76** [comment]
should be fixed for now
