### ISSUE TITLE
Obsolete regex settings

### ISSUE THREAD

**Issue by praise-you** [YunoHost-Apps/airsonic_ynh#39]
Hi, while installing the application I got this message. I'm sure if you're aware of it, that's why I'm creating this issue:

> /!\ Packagers! This app is still using the skipped/protected/unprotected_uris/regex settings which are now obsolete and deprecated... Instead, you should use the new helpers 'ynh_permission_{create,urls,update,delete}' and the 'visitors' group to initialize the public/private access. Check out the documentation at the bottom of yunohost.org/groups_and_permissions to learn how to use the new permission mechanism.

Thanks

**Comment by yalh76** [comment]
should be fixed for now
