### ISSUE TITLE
413 (Request Entity Too Large) on .zip upload via interface 

### ISSUE THREAD

**Issue by colmoneill** [YunoHost-Apps/airsonic_ynh#4]
Hi, thanks for the ynh_ package of airsonic !
It's been working great for me up to now, but I've ran into a config item I don't know where to change; when I attempt to upload a .zip through the airsonic interface, I receive the 413 error as shown below:

![Screenshot from 2019-07-17 16-33-44](https://user-images.githubusercontent.com/2122318/61389524-fd5dbc80-a8b0-11e9-87f8-0d7ee18fc073.png)

I'm certain I can change this in a configuration somewhere, but I'm still new to ynh, so would you say this is to do with a general ynh ngnix config or one specific to airsonic_ynh ?

Thanks again,

All the best !

**Comment by colmoneill** [comment]
Hi, thanks for taking this issue into consideration, meanwhile, I have realised that actually no size of .zip file is accepted by the web ui for upload. Any .zip file size triggers the 413. Hope this helps identify the issue.

Thanks again,

All the best

**Comment by Gofannon** [comment]
Hello,

Oh well, there might be a different issue then and the modification made in the "testing" versions will not correct it.

Could you try it anyway if you have the knowledge and time?
How to install/upgrade it here: https://github.com/YunoHost-Apps/airsonic_ynh#developers-info
